// Generated by CoffeeScript 1.6.3
var colorToString, colorsBetweenInclusive, randomColor;

randomColor = function() {
  var r;
  r = function() {
    return Math.random() * 224;
  };
  return [r(), r(), r()];
};

colorToString = function(color) {
  return "rgb(" + color.map(Math.floor).join(",") + ")";
};

colorsBetweenInclusive = function(colorFrom, colorTo, amount) {
  var colorSteps, _i, _results;
  colorSteps = [0, 1, 2].map(function(idx) {
    return numbersBetweenInclusive(colorFrom[idx], colorTo[idx], amount);
  });
  return (function() {
    _results = [];
    for (var _i = 0; 0 <= amount ? _i < amount : _i > amount; 0 <= amount ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this).map(function(step) {
    return [0, 1, 2].map(function(idx) {
      return colorSteps[idx][step];
    });
  });
};
