// Generated by CoffeeScript 1.6.3
var onvscroll;

onvscroll = function(cb) {
  var eventName, lastPoint, mozilla, touch;
  mozilla = $.browser.mozilla;
  touch = window.ontouchstart !== void 0;
  eventName = mozilla ? 'wheel' : 'mousewheel';
  $(window).on(eventName, function(event) {
    var delta, original, _ref, _ref1;
    original = event.originalEvent;
    delta = (_ref = (_ref1 = original.wheelDeltaY) != null ? _ref1 : original.deltaY) != null ? _ref : original.wheelDelta;
    if (mozilla) {
      delta = -delta;
    }
    return cb(delta < 0);
  });
  if (touch) {
    lastPoint = null;
    $(window).on('touchstart', function(event) {
      return lastPoint = event.originalEvent.touches[0].pageY;
    });
    $(window).on('touchmove', function(event) {
      var delta;
      if (!lastPoint) {
        return;
      }
      delta = event.originalEvent.touches[0].pageY - lastPoint;
      return cb(delta < 0);
    });
    return $(window).on('touchend', function() {
      return lastPoint = null;
    });
  }
};
